[project]
name = "tiny-dreamer-4"
version = "0.1.0"
description = "Dreamer 4 implementation in pure Jax"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "einops",
    "flax",
    "hydra-core",
    "imageio[ffmpeg]",
    "jax[cuda12]",
    "jaxlpips",
    "matplotlib",
    "optax",
    "tqdm",
    "wandb",
    "procgen-mirror",
    "tyro>=1.0.0",
    "array-record>=0.8.3",
    "grain>=0.2.15",
    "ipykernel>=7.1.0",
    "reactor-runtime>=0.0.4",
    "pandas>=2.3.3",
    "awscli>=1.27.0",
    "decord>=0.6.0",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
]


[tool.setuptools.packages.find]
where = ["."]

[tool.uv.sources]
optax = { git = "https://github.com/google-deepmind/optax.git" }

[tool.setuptools]
package-dir = {"" = "."}
