// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: open-dreamer v0.1.0

import { Reactor, FileRef } from "@reactor-team/js-sdk";
export { FileRef };

export const MODEL_NAME = "reactor/open-dreamer" as const;
export const MODEL_VERSION = "v0.1.0" as const;

/**
 * Preset media tracks for the OpenDreamer model.
 *
 * Declared in the model's OpenAPI schema and passed to the SDK as
 * `modelTracks` so the transport can prepare the SDP offer in
 * parallel with session polling (faster first-frame latency).
 */
export const OpenDreamerTracks = [
  { name: "main_video", kind: "video", direction: "recvonly" },
] as const;

/** Track names the client can subscribe to (recvonly, from the client's perspective). */
export type OpenDreamerRecvTrackName = "main_video";

/** Set currently-held keys */
export interface OpenDreamerSendKeyboardStateParams {
  /** @default false */

  w?: boolean;
  /** @default false */

  a?: boolean;
  /** @default false */

  s?: boolean;
  /** @default false */

  d?: boolean;
  /** @default false */

  space?: boolean;
  /** @default false */

  shift?: boolean;
  /** @default false */

  ctrl?: boolean;
  /** @default false */

  e?: boolean;
  /** @default false */

  q?: boolean;
  /** @default false */

  f?: boolean;
  /** @default false */

  n1?: boolean;
  /** @default false */

  n2?: boolean;
  /** @default false */

  n3?: boolean;
  /** @default false */

  n4?: boolean;
  /** @default false */

  n5?: boolean;
  /** @default false */

  n6?: boolean;
  /** @default false */

  n7?: boolean;
  /** @default false */

  n8?: boolean;
  /** @default false */

  n9?: boolean;
  /** @default false */

  f3?: boolean;
}

/** Set mouse buttons; accumulate camera delta */
export interface OpenDreamerSendMouseStateParams {
  /** @default false */

  left?: boolean;
  /** @default false */

  right?: boolean;
  /** @default false */

  middle?: boolean;
  /** @default 0 */

  dx?: number;
  /** @default 0 */

  dy?: number;
}

/** Accumulate scroll-wheel ticks */
export interface OpenDreamerSendMouseWheelParams {
  /** @default 0 */

  dwheel?: number;
}

/** Switch the streamed video between the live playable game and the AI-generated world. Pass `enable=true` for the generated world, `enable=false` for the live game. Reflected back in `world_status`. */
export interface OpenDreamerSwitchToPolicyParams {
  /** @default true */

  enable?: boolean;
}

/** Generate a fresh world and start in the live playable game, discarding the current scene (including one started from an uploaded image). Emits `world_status` with `loading=true` while the world is prepared. */
export interface OpenDreamerNewSceneParams {
  /** @default -1 */

  seed?: number;
}

/** Start a fresh AI-generated world from an uploaded image and begin exploring it. Emits `world_status` with `loading=true` while the scene is prepared, then `use_policy=true` once the generated world is live. */
export interface OpenDreamerSetConditioningImageParams {
  /** Reference to a file uploaded via the Reactor presigned-URL protocol. */

  image: FileRef;
}

/**
 * Emitted continuously with the session's live status.
 *
 * Lets the client show a loading screen instead of a frozen frame and keep its view toggle in sync with server-driven switches (for example, after starting a scene from an uploaded image).
 */
export interface OpenDreamerWorldStatusMessage {
  type: "world_status";
  /** True while a new world is being prepared (on connect, or after a new-scene or image request). The video is not live yet — show a loading screen until this is False. */

  loading: boolean;
  /** True when the streamed video is the AI-generated world, False when it is the live playable game. Mirror this in the client's view toggle. */

  use_policy: boolean;
}

export type OpenDreamerMessage = OpenDreamerWorldStatusMessage;

/**
 * Options for creating a OpenDreamerModel (model name is set automatically).
 *
 * Derived from `Reactor`'s own constructor options with `modelName`
 * and `modelTracks` removed — those are supplied by this class.
 * Any new option the SDK adds appears here automatically on the
 * next `defaultSdkVersion` bump.
 */
export type OpenDreamerOptions = Omit<
  ConstructorParameters<typeof Reactor>[0],
  "modelName" | "modelTracks"
>;

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Strongly-typed client for the OpenDreamer model.
 *
 * Extends {@link Reactor} with the model name (and modelTracks) baked into the
 * constructor, so every public method on Reactor — `connect`, `disconnect`,
 * `sendCommand`, `on`/`off`, `getStats`, `publishTrack`/`unpublishTrack`,
 * etc. — is reachable directly on the instance. The schema-derived sugar
 * below adds typed wrappers for every declared event, message, and track.
 */

export class OpenDreamerModel extends Reactor {
  constructor(options?: OpenDreamerOptions) {
    super({
      ...options,
      modelName: MODEL_NAME,
      modelTracks: [...OpenDreamerTracks],
    });
  }

  /** @deprecated The model client now extends `Reactor` directly — call methods on `this` instead. This accessor returns `this` for backwards compatibility and will be removed in a future major release. */

  get reactor(): this {
    return this;
  }

  /**
   * Set currently-held keys
   * @param params - Set currently-held keys
   */

  async sendKeyboardState(
    params: OpenDreamerSendKeyboardStateParams
  ): Promise<void> {
    await this.sendCommand("send_keyboard_state", params);
  }

  /**
   * Set mouse buttons; accumulate camera delta
   * @param params - Set mouse buttons; accumulate camera delta
   */

  async sendMouseState(params: OpenDreamerSendMouseStateParams): Promise<void> {
    await this.sendCommand("send_mouse_state", params);
  }

  /**
   * Accumulate scroll-wheel ticks
   * @param params - Accumulate scroll-wheel ticks
   */

  async sendMouseWheel(params: OpenDreamerSendMouseWheelParams): Promise<void> {
    await this.sendCommand("send_mouse_wheel", params);
  }

  /**
   * Switch the streamed video between the live playable game and the AI-generated world. Pass `enable=true` for the generated world, `enable=false` for the live game. Reflected back in `world_status`.
   * @param params - Switch the streamed video between the live playable game and the AI-generated world. Pass `enable=true` for the generated world, `enable=false` for the live game. Reflected back in `world_status`.
   */

  async switchToPolicy(params: OpenDreamerSwitchToPolicyParams): Promise<void> {
    await this.sendCommand("switch_to_policy", params);
  }

  /**
   * Generate a fresh world and start in the live playable game, discarding the current scene (including one started from an uploaded image). Emits `world_status` with `loading=true` while the world is prepared.
   * @param params - Generate a fresh world and start in the live playable game, discarding the current scene (including one started from an uploaded image). Emits `world_status` with `loading=true` while the world is prepared.
   */

  async newScene(params: OpenDreamerNewSceneParams): Promise<void> {
    await this.sendCommand("new_scene", params);
  }

  /**
   * Start a fresh AI-generated world from an uploaded image and begin exploring it. Emits `world_status` with `loading=true` while the scene is prepared, then `use_policy=true` once the generated world is live.
   * @param params - Start a fresh AI-generated world from an uploaded image and begin exploring it. Emits `world_status` with `loading=true` while the scene is prepared, then `use_policy=true` once the generated world is live.
   */

  async setConditioningImage(
    params: OpenDreamerSetConditioningImageParams
  ): Promise<void> {
    await this.sendCommand("set_conditioning_image", params);
  }

  /**
   * Subscribe to typed model messages.
   * @param handler - Called with a discriminated OpenDreamerMessage
   * @returns Unsubscribe function
   */

  onMessage(handler: (message: OpenDreamerMessage) => void): () => void {
    const wrappedHandler = (raw: unknown) => {
      handler(_unwrapMessage<OpenDreamerMessage>(raw));
    };
    this.on("message", wrappedHandler);
    return () => this.off("message", wrappedHandler);
  }

  /**
   * Subscribe to "world_status" messages only.
   * @returns Unsubscribe function
   */

  onWorldStatus(
    handler: (message: OpenDreamerWorldStatusMessage) => void
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "world_status")
        handler(msg as OpenDreamerWorldStatusMessage);
    });
  }

  /**
   * Subscribe to the "main_video" recvonly video track the model publishes.
   *
   * The handler fires once the model starts publishing this track; it receives the live MediaStreamTrack and the parent MediaStream (useful for attaching to a `<video>` / `<audio>` element via `srcObject`).
   * @param handler - Called with the received track and its stream
   * @returns Unsubscribe function
   */

  onMainVideo(
    handler: (track: MediaStreamTrack, stream: MediaStream) => void
  ): () => void {
    const wrapped = (name: string, t: MediaStreamTrack, s: MediaStream) => {
      if (name === "main_video") handler(t, s);
    };
    this.on("trackReceived", wrapped);
    return () => this.off("trackReceived", wrapped);
  }
}
