// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: open-dreamer v0.1.0

"use client";

import { type ReactElement } from "react";
import {
  ReactorProvider,
  useReactor,
  useReactorMessage,
  ReactorView,
  type ReactorViewProps,
} from "@reactor-team/js-sdk";
import {
  MODEL_NAME,
  OpenDreamerTracks,
  type OpenDreamerOptions,
  type OpenDreamerSendKeyboardStateParams,
  type OpenDreamerSendMouseStateParams,
  type OpenDreamerSendMouseWheelParams,
  type OpenDreamerSwitchToPolicyParams,
  type OpenDreamerNewSceneParams,
  type OpenDreamerSetConditioningImageParams,
  type OpenDreamerMessage,
  type OpenDreamerWorldStatusMessage,
  type OpenDreamerRecvTrackName,
} from "./open-dreamer.gen";

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Props for the {@link OpenDreamerProvider} component.
 *
 * Derived from `ReactorProvider`'s own props, with `modelName` and
 * `modelTracks` stripped — those are supplied by this provider.
 */
export type OpenDreamerProviderProps = Omit<
  Parameters<typeof ReactorProvider>[0],
  "modelName" | "modelTracks"
>;

/**
 * Provider for the OpenDreamer model.
 *
 * Wraps {@link ReactorProvider} with `modelName` and `modelTracks` pre-configured from the
 * generated constants. Drop this near the top of your tree, then use
 * {@link useOpenDreamer} and the `useOpenDreamer<Message>` hooks below it.
 */
export function OpenDreamerProvider({
  children,
  ...rest
}: OpenDreamerProviderProps): ReactElement {
  return (
    <ReactorProvider
      {...rest}
      modelName={MODEL_NAME}
      modelTracks={[...OpenDreamerTracks]}
    >
      {children}
    </ReactorProvider>
  );
}

/**
 * Access the OpenDreamer model as typed commands bound to the nearest
 * {@link OpenDreamerProvider}.
 *
 * Returns the full action surface — every public field on the SDK's
 * `ReactorStore` (`status`, `sessionId`, `connect`, `disconnect`,
 * `sendCommand`, `uploadFile`, `publish`, `unpublish`, `reconnect`,
 * …) is exposed automatically, alongside one typed method per
 * model event.
 *
 * Fields are pulled off the store one at a time so Zustand's
 * shallow-equality selector keeps each subscription scoped — a
 * component reading only `status` doesn't re-render when
 * `sessionExpiration` changes. Future SDK releases that add new
 * store fields flow into this hook on the next codegen run with no
 * hand-edit (the field list is derived from `js-sdk`'s d.ts via
 * `loadReactorStoreFieldsFromDts` in `sdk-surface.ts`).
 */
export function useOpenDreamer() {
  const connect = useReactor((s) => s.connect);
  const connectOptions = useReactor((s) => s.connectOptions);
  const disconnect = useReactor((s) => s.disconnect);
  const downloadClipAsFile = useReactor((s) => s.downloadClipAsFile);
  const jwtToken = useReactor((s) => s.jwtToken);
  const lastError = useReactor((s) => s.lastError);
  const publish = useReactor((s) => s.publish);
  const reconnect = useReactor((s) => s.reconnect);
  const requestClip = useReactor((s) => s.requestClip);
  const requestRecording = useReactor((s) => s.requestRecording);
  const sendCommand = useReactor((s) => s.sendCommand);
  const sessionExpiration = useReactor((s) => s.sessionExpiration);
  const sessionId = useReactor((s) => s.sessionId);
  const status = useReactor((s) => s.status);
  const tracks = useReactor((s) => s.tracks);
  const unpublish = useReactor((s) => s.unpublish);
  const uploadFile = useReactor((s) => s.uploadFile);

  return {
    connect,
    connectOptions,
    disconnect,
    downloadClipAsFile,
    jwtToken,
    lastError,
    publish,
    reconnect,
    requestClip,
    requestRecording,
    sendCommand,
    sessionExpiration,
    sessionId,
    status,
    tracks,
    unpublish,
    uploadFile,
    sendKeyboardState: (
      params: OpenDreamerSendKeyboardStateParams
    ): Promise<void> => sendCommand("send_keyboard_state", params),
    sendMouseState: (params: OpenDreamerSendMouseStateParams): Promise<void> =>
      sendCommand("send_mouse_state", params),
    sendMouseWheel: (params: OpenDreamerSendMouseWheelParams): Promise<void> =>
      sendCommand("send_mouse_wheel", params),
    switchToPolicy: (params: OpenDreamerSwitchToPolicyParams): Promise<void> =>
      sendCommand("switch_to_policy", params),
    newScene: (params: OpenDreamerNewSceneParams): Promise<void> =>
      sendCommand("new_scene", params),
    setConditioningImage: (
      params: OpenDreamerSetConditioningImageParams
    ): Promise<void> => sendCommand("set_conditioning_image", params),
  };
}

/**
 * Subscribe to any OpenDreamer message with a fully-typed handler.
 * The handler receives a discriminated OpenDreamerMessage.
 */
export function useOpenDreamerMessage(
  handler: (message: OpenDreamerMessage) => void
): void {
  useReactorMessage((msg: unknown) =>
    handler(_unwrapMessage<OpenDreamerMessage>(msg))
  );
}

/**
 * Subscribe to "world_status" messages only.
 * Handler receives a fully-typed OpenDreamerWorldStatusMessage.
 */
export function useOpenDreamerWorldStatus(
  handler: (message: OpenDreamerWorldStatusMessage) => void
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<OpenDreamerMessage>(msg);
    if (m.type === "world_status") {
      handler(m as OpenDreamerWorldStatusMessage);
    }
  });
}

/**
 * Subscribe to a recvonly MediaStreamTrack the model publishes, by name.
 *
 * Returns `undefined` until the model emits the track, then the live track for the lifetime of the connection. `name` is constrained to the model's declared recvonly channels — use one of `OpenDreamerRecvTrackName`.
 * @param name - A recvonly track name declared by the model
 * @returns The live MediaStreamTrack, or `undefined` until received
 */
export function useOpenDreamerTrack(
  name: OpenDreamerRecvTrackName
): MediaStreamTrack | undefined {
  return useReactor((s) => s.tracks[name]);
}

export type OpenDreamerMainVideoViewProps = Omit<ReactorViewProps, "track">;

/**
 * Render the model's "main_video" recvonly video track in a `<video>` element.
 *
 * Thin wrapper around `<ReactorView>` with `track` pre-bound. Accepts every other `ReactorViewProps` (`audioTrack`, `className`, `style`, `videoObjectFit`, `muted`, …). Must be rendered inside `<OpenDreamerProvider>`.
 */
export function OpenDreamerMainVideoView(
  props: OpenDreamerMainVideoViewProps
): ReactElement {
  return <ReactorView {...props} track="main_video" />;
}
