defaults:
  - _self_

name: minecraft_vpt

array_record_path: /home/minecraft-vpt/contractor_demos/8xx_Jun_29/
index_max: 10000

B: 4
T: 4
H: 360
W: 640
C: 3

num_binary_actions: 23  # keyboard actions
categorical_action_dim: 121  # mouse actions
continuous_action_dim: 0

dataset_mean: [0.5, 0.5, 0.5]
dataset_std: [0.288675, 0.288675, 0.288675]

p_include_reward: 0.0
