defaults:
  - _self_

name: minecraft_vpt
data_type: video

array_record_path: /home/data/arrayrecords-mp4
index_max: 1500
num_max_samples: -1

dataloader_cfg:
  B: 16
  T: 32
  num_workers: 16
  prefetch_buffer_size: 10
  device_prefetch_buffer_size: 1
  short_T: 4
  long_T: 4
  long_ratio: 0.0
  start_step: 0
  dtype: bfloat16

H: 360
W: 640
C: 3

padding_H: [0, 0]
padding_W: [0, 0]
patch_size: 20

num_binary_actions: 23  # keyboard actions
categorical_action_dim: 121  # mouse actions
continuous_action_dim: 0

p_include_reward: 0.0
