defaults:
  - _self_

name: minecraft_vpt_latent
data_type: latent
array_record_path: /mnt/data/tokenized_data  
index_max: 30
num_max_samples: -1

num_binary_actions: 23
categorical_action_dim: 121
continuous_action_dim: 0

dataloader_cfg:
  B: 64
  T: 32
  num_workers: 16
  prefetch_buffer_size: 10
  device_prefetch_buffer_size: 1
  short_T: 4
  long_T: 4
  long_ratio: 0.0
  start_step: 0
  dtype: bfloat16

H: 360
W: 640
C: 3
