defaults:
  - _self_

name: minecraft_vpt
data_type: video

array_record_path: /home/ubuntu/minecraft-vpt/arrayrecords-mp4
index_max: 1500

dataloader_cfg:
  B: 8
  num_workers: 16
  prefetch_buffer_size: 10
  device_prefetch_buffer_size: 1
  short_T: 4
  long_T: 4
  long_ratio: 0.0
  start_step: 0
  dtype: bfloat16

H: 360
W: 640
C: 3

padding_H: [4, 4]
padding_W: [0, 0]
patch_size: 16

num_binary_actions: 23  # keyboard actions
categorical_action_dim: 121  # mouse actions
continuous_action_dim: 0

dataset_mean: [0.2241, 0.2348, 0.2086]
dataset_std: [0.1809, 0.1874, 0.2282]

p_include_reward: 0.0
