defaults:
  - common

run_name: train_bc_rew_flippedrew
tokenizer_ckpt: ./logs/tokenizer/checkpoints
pretrained_dyn_ckpt: ./logs/train_dynamics/checkpoints
ckpt_save_every: 1e5

use_wandb: false

dataset:
  B: 64
  diversify_data: true

action_dim: 4

patch: 4
enc_n_latents: 16
enc_d_bottleneck: 32
d_model_enc: 64
d_model_dyn: 128
enc_depth: 8
dec_depth: 8
dyn_depth: 8
n_heads: 4
packing_factor: 2
n_register: 4
n_agent: 1
agent_space_mode: wm_agent

k_max: 8
bootstrap_start: 5000
self_fraction: 0.25

max_steps: 1e9
log_every: 5000
lr: 1e-4

write_video_every: 1e5

L: 2
num_reward_bins: 101
reward_log_low: -3.0
reward_log_high: 3.0
n_tasks: 128
use_task_ids: true

loss_weight_shortcut: 1.0
loss_weight_policy: 0.3
loss_weight_reward: 0.3