defaults:
  - _self_

run_name: ???
use_wandb: true
dataset: ???
scaling_tokens_per_param: 0.0
scaling_flops_budget: 0.0

# Checkpointing
ckpt:
  max_to_keep: 1
  save_interval_steps: 10_000
  max_steps: ${max_steps}

# Logging
logger:
  run_name: ${run_name}
  use_wandb: ${use_wandb}
  wandb_entity: Null
  wandb_project: tiny_dreamer_4
  log_every: 100
  max_steps: ${max_steps}
  log_gradients: false

# Precision
dtype: bfloat16
param_dtype: bfloat16

# Parallel
parallel_strategy: data  # data | fsdp | tp | sp

# Random seed
seed: 0

# Hydra
hydra:
  run:
    dir: /mnt/data/logs/${run_name}
