defaults:
  - _self_

run_name: ???
use_wandb: False
dataset: ???

# Checkpointing
ckpt:
  max_to_keep: 2
  save_interval_steps: 10_000
  max_steps: ${max_steps}

# Logging
logger:
  run_name: ${run_name}
  use_wandb: ${use_wandb}
  wandb_entity: Null
  wandb_project: tiny_dreamer_4
  log_every: 100
  max_steps: ${max_steps}
  log_gradients: false

# Precision
dtype: bfloat16
param_dtype: float32

# Parallel
parallel_strategy: data  # data | fsdp | tp

# Random seed
seed: 0

# Hydra
hydra:
  run:
    dir: logs/${run_name}
