defaults:
  - common
  - _self_
  - dataset: coinrun

run_name: dynamics
tokenizer_ckpt: logs/tokenizer/checkpoints/

ckpt:
  max_to_keep: 2
  save_interval_steps: 10_000

dataset:
  B: 256

dynamics:
    d_model: 1024
    d_bottleneck: 16
    action_dim: 16
    depth: 12
    n_heads: 8
    n_kv_heads: 2
    packing_factor: 2
    n_register: 32
    qk_norm_type: quest
    rope_theta: 10000.0
    time_every: 4
    mlp_ratio: 4
    dropout_rate: 0.05
    k_max: 128
    dtype: ${dtype}
    param_dtype: ${param_dtype}
    tokenizer_ckpt: ${tokenizer_ckpt}

bootstrap_start: 5_000
self_fraction: 0.25

max_steps: 300_000

lr_schedule:
  schedule_type: wsd  # constant | wsd | cos
  lr: 3e-4  # constant LR or peak LR for schedules
  init_lr: 0.0
  lr_end: 0.0
  warmup_steps: 50_000
  wsd_decay_steps: 20_000
  max_steps: ${max_steps}

optimizer:
  optimizer_type: adamw
  b1: 0.9
  b2: 0.9
  weight_decay: 1e-4

write_video_every: 5_000