defaults:
  - common
  - _self_

run_name: dynamics
tokenizer_ckpt: 'logs/tokenizer/checkpoints'
ckpt_save_every: 50_000
tokenizer:
  run_name: ${run_name}_tokenizer_proxy
  tokenizer_ckpt: ${tokenizer_ckpt}  # Pass through if needed by TokenizerConfig logic, though usually loaded manually
  ckpt_save_every: ${ckpt_save_every}
  
  dataset:
    B: 64
    diversify_data: true

  encoder:
    n_latents: 16
    d_bottleneck: 32
    d_model: 64
    n_heads: 4
    n_kv_heads: 2
    depth: 8
    patch_size: 4
  
  decoder:
    d_model: 64
    n_heads: 4
    n_kv_heads: 2
    n_latents: 16
    patch_size: 4
    depth: 8
  
  patch_size: 4

# Dynamics specific
d_model_dyn: 128
dyn_depth: 8
n_heads: 4
n_kv_heads: 2
packing_factor: 2
n_register: 4
n_agent: 1

k_max: 8
bootstrap_start: 5_000
self_fraction: 0.25

max_steps: 1_000_000_000
log_every: 500
lr: 1e-3

write_video_every: 5_000