defaults:
  - common
  - _self_

run_name: bc_rew
tokenizer_ckpt: "logs/tokenizer/checkpoints"
dynamics_ckpt: "logs/dynamics/checkpoints"
ckpt_save_every: 100_000

dataset:
  B: 64
  T: 32
  diversify_data: true

action_dim: 16
n_agent: 4

# Training hyperparameters
bootstrap_start: 5000
self_fraction: 0.25

max_steps: 1_000_000_000
log_every: 10
write_video_every: 500

# Learning rates
lr_policy: ${lr_dynamics}
lr_reward: ${lr_dynamics}
lr_dynamics: 1e-4
dynamics_loss_weight: 0.1

# Multi-token prediction settings
L: ${n_agent}
num_reward_bins: 101
reward_log_low: -5.0  
reward_log_high: 3.0
n_tasks: 128
use_task_ids: true

# Loss weighting
loss_weight_shortcut: 1.0
loss_weight_policy: 0.3
loss_weight_reward: 0.3