defaults:
  - common
  - _self_

run_name: policy
bc_rew_ckpt: "logs/train_heads_r10p1s1_mtp8_oversample_11bins_fixrew/checkpoints"
ckpt_save_every: 10_000

action_dim: 16
n_agent: 8

max_steps: 100_000
log_every: 100
lr: 1e-4

write_video_every: 1

L: ${n_agent}
num_reward_bins: 11
reward_log_low: 0.0
reward_log_high: 3.0
num_value_bins: 101
n_tasks: 128
use_task_ids: true

# Imagination RL 
gamma: 0.9
lambda_: 0.95
horizon: 32
context_length: 16
imagination_d: 0.25
alpha: 0.5
beta: 0.3