defaults:
  - common
  - _self_

run_name: policy
bc_rew_ckpt: logs/bc_rew/checkpoints 
ckpt_save_every: 100_000

dataset:
  B: 64
  diversify_data: true

action_dim: 4

patch: 4
enc_n_latents: 16
enc_d_bottleneck: 32
d_model_enc: 64
d_model_dyn: 128
enc_depth: 8
dec_depth: 8
dyn_depth: 8
n_heads: 4
n_kv_heads: 2
qk_norm_type: null  # options: qknorm, quest, null
use_rope: true
rope_theta: 10000.0
packing_factor: 2
n_register: 4
n_agent: 1
agent_space_mode: wm_agent

k_max: 8

max_steps: 100_000
log_every: 100
lr: 1e-4

write_video_every: 1
visualize_every: 1

L: 2
num_reward_bins: 101
reward_log_low: -3.0
reward_log_high: 3.0
num_value_bins: 101
n_tasks: 128
use_task_ids: true

gamma: 0.9
lambda_: 0.95
horizon: 32
context_length: 16
imagination_d: 0.25
alpha: 0.5
beta: 0.3

eval_every: 5_000
eval_episodes: 64
eval_horizon: 32
eval_batch_size: 64
max_eval_examples_to_plot: 4