defaults:
  - common
  - dataset: coinrun
  - _self_

run_name: tokenizer

dataset:
  B: 256
  T: 8

ckpt:
  max_to_keep: 1
  save_interval_steps: 10_000

tokenizer:
  encoder:
    n_latents: 16
    d_bottleneck: 16
    depth: 5
    d_model: ${mul:64,${sum:${tokenizer.encoder.depth},${tokenizer.decoder.depth}}}
    n_heads: ${floordiv:${tokenizer.encoder.d_model},64}
    n_kv_heads: ${max:1,${floordiv:${tokenizer.encoder.n_heads},8}}
    dropout_rate: 0.0

    qk_norm_type: qknorm  # qknorm | quest | null
    rope_theta: 10000.0
    time_every: 4
    mae_p_min: 0.0
    mae_p_max: 0.9
    patch_size: 20
    use_residual_lambdas: true
    use_bias: false
    use_rmsnorm_scale: true
    dtype: ${dtype}
    param_dtype: ${param_dtype}

    dataset_mean: ${dataset.dataset_mean}
    dataset_std: ${dataset.dataset_std}

  decoder:
    n_latents: ${tokenizer.encoder.n_latents}
    d_bottleneck: ${tokenizer.encoder.d_bottleneck}
    depth: ${tokenizer.encoder.depth}
    d_model: ${tokenizer.encoder.d_model}
    n_heads: ${tokenizer.encoder.n_heads}
    n_kv_heads: ${tokenizer.encoder.n_kv_heads}
    dropout_rate: ${tokenizer.encoder.dropout_rate}
    qk_norm_type: ${tokenizer.encoder.qk_norm_type}
    rope_theta: ${tokenizer.encoder.rope_theta}
    time_every: ${tokenizer.encoder.time_every}
    H: ${dataset.H}
    W: ${dataset.W}
    patch_size: ${tokenizer.encoder.patch_size}
    d_patch: ${mul:${tokenizer.decoder.patch_size},${tokenizer.decoder.patch_size},${dataset.C}}
    use_residual_lambdas: ${tokenizer.encoder.use_residual_lambdas}
    use_bias: ${tokenizer.encoder.use_bias}
    use_rmsnorm_scale: ${tokenizer.encoder.use_rmsnorm_scale}
    dtype: ${dtype}
    param_dtype: ${param_dtype}

    dataset_mean: ${dataset.dataset_mean}
    dataset_std: ${dataset.dataset_std}

max_steps: 300_000
tokenizer_loss_type: mse  # mse | mae

lr_schedule:
  schedule_type: wsd  # constant | wsd | cos
  lr: 0.003  # constant LR or peak LR for schedules
  init_lr: 0.0
  lr_end: 0.0
  warmup_ratio: 0.05
  decay_ratio: 0.5
  max_steps: ${max_steps}

optimizer:
  optimizer_type: muon
  weight_decay: 0.1
  # AdamW params (for embeddings/biases)
  adam_lr_ratio: 1.0
  adam_b1: 0.9
  adam_b2: 0.99
  mup_scaling: true
  mup_base_dim: 640
  # Muon params (for 2D matrix weights)
  muon_beta: 0.95
  muon_ns_steps: 5
  muon_nesterov: true

lpips_weight: 0.2
lpips_frac: 0.5
visualize_every: 1000
