defaults:
  - dataset: minecraft_vpt
  - _self_

tokenizer_ckpt: /mnt/data/minecraft-vpt/models/tokenizer-500M/checkpoints       # Required: path to pretrained tokenizer checkpoint
output_dir: /mnt/data/ema_tokenized_data            # Required: output directory for latent shards
records_per_shard: 5000
seed: 0
parallel_strategy: data

hydra:
  run:
    dir: .
