defaults:
  - common
  - _self_

run_name: tokenizer
ckpt_max_to_keep: 5
ckpt_save_every: 10_000

patch_size: 4

dataset:
  source: "custom"
  array_record_path: "datasets/coinrun_episodes/train"
  B: 16
  T: 16
  H: 64
  W: 64
  C: 3

encoder:
  n_latents: 16
  d_bottleneck: 32
  d_model: 256
  n_heads: 8
  n_kv_heads: 4
  depth: 8
  dropout_rate: 0.05
  qk_norm_type: null  # options: qknorm, quest, null
  rope_theta: 10000.0
  time_every: 4
  mae_p_min: 0.0
  mae_p_max: 0.9

decoder:
  d_model: ${encoder.d_model}
  n_heads: ${encoder.n_heads}
  n_kv_heads: ${encoder.n_kv_heads}
  n_latents: ${encoder.n_latents}
  depth: ${encoder.depth}
  dropout_rate: ${encoder.dropout_rate}
  qk_norm_type: ${encoder.qk_norm_type}
  rope_theta: ${encoder.rope_theta}
  time_every: ${encoder.time_every}

lr: 3e-4
max_steps: 1_000_000_000
log_every: 1000
lpips_weight: 0.2
lpips_frac: 0.5
visualize_every: 4000