program: scripts/train_dynamics.py
method: random

metric:
  name: eval/diffusion/psnr
  goal: maximize

parameters:
  lr_schedule.lr:
    values: [0.004, 0.003, 0.002]

  lr_schedule.warmup_ratio:
    values: [0.05]

  lr_schedule.decay_ratio:
    values: [0.4, 0.5]

  optimizer.adam_lr_ratio:
    values: [0.1, 1.]

  optimizer.adam_b1:
    values: [0.99, 0.95, 0.9]

  optimizer.adam_b2:
    values: [0.99, 0.999] 

  optimizer.weight_decay:
    values: [0.1]

  optimizer.mup_scaling:
    value: false

  dynamics.n_register:
    values: [16, 32]
  
  # dynamics.k_max:
  #   values: [8, 64]

  # dynamics.dropout_rate:
  #   values: [0.05]

  dynamics.n_heads:
    values: [4, 8]
  
  dynamics.n_kv_heads:
    values: [2, 4]
  
  ckpt.max_to_keep:
    value: 0

  use_wandb:
    value: true

  max_steps:
    value: 20_000
    
  dataset.B:
    value: 256

command:
  - uv
  - run
  - ${program}
  - ${args_no_hyphens}
  - run_name=lr${lr_schedule.lr}_warmup${lr_schedule.warmup_ratio}_decay${lr_schedule.decay_ratio}_adam_lr${optimizer.adam_lr_ratio}_b1${optimizer.adam_b1}_b2${optimizer.adam_b2}_nreg${dynamics.n_register}_nh${dynamics.n_heads}_nkv${dynamics.n_kv_heads}