program: scripts/train_dynamics.py
entity: pal
project: tiny_dreamer_4
method: grid

metric:
  name: train/flow_mse_sequence
  goal: minimize

parameters:
  lr_schedule.lr:
    values: [1e-3, 6e-4, 3e-4, 1e-4]
  
  optimizer.muon_beta:
    values: [0.99, 0.95]

  max_steps:
    value: 100_000

  dumo_beta:
    value: 0.5

  dynamics.depth:
    value: 16
  

command:
  - uv
  - run
  - ${program}
  - ${args_no_hyphens}
  - run_name=fixed_d_model${dynamics.d_model}_n_register${dynamics.n_register}_depth${dynamics.depth}_dropout${dynamics.dropout_rate}_qk_norm${dynamics.qk_norm_type}_rope_theta${dynamics.rope_theta}_n_heads${dynamics.n_heads}_n_kv_heads${dynamics.n_kv_heads}
