program: scripts/train_dynamics.py
method: random

metric:
  name: eval/diffusion/psnr
  goal: maximize

parameters:
  max_lr:
    values: [1e-4, 3e-4]

  dynamics.d_model:
    values: [256, 512]
  
  dynamics.n_register:
    values: [16, 32]
  
  dynamics.depth:
    values: [6, 12]

  dynamics.k_max:
    values: [8, 64]

  dynamics.dropout_rate:
    values: [0.05]

  dynamics.qk_norm_type:
    values: [null, qknorm, quest]

  dynamics.rope_theta:
    values: [10000.0, 150000.0]
  
  dynamics.n_heads:
    values: [4, 8]
  
  dynamics.n_kv_heads:
    values: [2, 4]

  use_wandb:
    value: true

  max_steps:
    value: 50000

command:
  - uv
  - run
  - ${program}
  - ${args_no_hyphens}
  - run_name=fixed_d_model${dynamics.d_model}_n_register${dynamics.n_register}_depth${dynamics.depth}_k_max${dynamics.k_max}_dropout${dynamics.dropout_rate}_qk_norm${dynamics.qk_norm_type}_rope_theta${dynamics.rope_theta}_n_heads${dynamics.n_heads}_n_kv_heads${dynamics.n_kv_heads}