program: scripts/train_tokenizer.py
method: random

metric:
  name: train/psnr
  goal: maximize

parameters:
  logger.log_every:
    value: 500

  dataset.B:
    value: 128
  #  values: [8, 16, 32, 64, 128, 256, 512]

  encoder.depth:
    value: 5

  encoder.dropout_rate:
    values: [0.001, 0.01, 0.05]

  encoder.qk_norm_type:
    values: [null, qknorm, quest]

  encoder.use_residual_lambdas:
    values: [true, false]
  
  encoder.use_rmsnorm_scale:
    values: [true, false]

  lr_schedule.lr:
    values: [0.01, 0.007, 0.005, 0.003, 0.002, 0.001]

  lr_schedule.warmup_ratio:
    values: [0.0, 0.033, 0.1, 0.2]

  lr_schedule.decay_ratio:
    values: [0.1, 0.2, 0.4]

  optimizer.adam_lr_ratio:
    values: [0.01, 0.1, 1.]

  optimizer.adam_b1:
    values: [0.99, 0.95, 0.9, 0.8]

  optimizer.adam_b2:
    values: [0.99, 0.95, 0.9, 0.8]

  optimizer.weight_decay:
    values: [0.0, 1e-4, 1e-2, 0.1, 0.2]

  optimizer.mup_scaling:
    value: false

  use_wandb:
    value: true

  max_steps:
    value: 25_000

command:
  - uv
  - run
  - ${program}
  - ${args_no_hyphens}
  - run_name=${encoder.dropout_rate}_${encoder.qk_norm_type}_${encoder.use_residual_lambdas}_${encoder.use_rmsnorm_scale}_lr${lr_schedule.lr}/{optimizer.adam_lr_ratio}_${lr_schedule.warmup_ratio}_${lr_schedule.decay_ratio}_b1${optimizer.adam_b1}_b2${optimizer.adam_b2}_wd${optimizer.weight_decay}    